---
server:
  port: 7070

spring:
  jpa:
    generate-ddl: true
    show-sql: true
  output:
    ansi:
      enabled: always

users:
  admins:
    - gjoinsey1@blogger.com
    - scrosi4@cam.ac.uk
    - scrosi4@cam.ac.uk

